name: Slack Notification Demo

on: [push]

jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2      
        uses: slackapi/slack-github-action@v1.18.0
        if: always()
        with:
          status: ${{ job.status }} # required
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
          
         
        
         