name: Slack Notification Demo

on: [push]

jobs:
  tests:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Slack Notification
        uses: slackapi/slack-github-action@v1.18.0
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Type:*\nComputer (laptop)"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*When:*\nSubmitted Aut 10"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Last Update:*\nMar 10, 2015 (3 years, 5 months)"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Reason:*\nAll vowel keys aren't working."
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Specs:*\n\"Cheetah Pro 15\" - Fast, really fast\""
                    }
                  ]
                }
              ]
            }
        env:         
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK